name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Karena kamu push ke main, bukan master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.211.106.193 << 'EOF'
            cd /home/ec2-user/uts_cc
            git pull origin main
            npm install
            pm2 restart uts-app || pm2 start app.js --name uts-app
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}